#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/Euglena_nr.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/euggr_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/Lvar2.2-protein.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/lytva_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_chlre_UP000006906.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/chlre_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_human_reviewed.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/human_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_mouse_UP000000589.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/mouse_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_nemve_UP000001593.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/nemve_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_phatc_UP000000759.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/phatc_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_strpu_UP000007110.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/strpu_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_tetts_UP000009168.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/tetts_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_xenla_UP000186698.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/xenla_hmmer_euNOG.mapping -l euNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_xenla_UP000186698.fasta.veNOG.hmmer.emapper.annotations -o  eggnog_mapping/xenla_hmmer_veNOG.mapping -l veNOG -s hmmer
#Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/brachionus_plicatilis_brapl_PRJNA422189.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/brapl_hmmer_euNOG.mapping -l euNOG -s hmmer
Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/xenla_XL9.1_XLgb_concat.fasta.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/xenla_hmmer_euNOG.mapping -l euNOG -s hmmer

Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/arath.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/arath.euNOG.mapping -l euNOG -s hmmer
Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/soybn.euNOG.hmmer.emapper.annotations -o  eggnog_mapping/soybn.euNOG.mapping -l euNOG -s hmmer

Rscript /project/cmcwhite/pipelines/MS_grouped_lookup/scripts/lookup_utils/format_emapper_output.R -f eggnog_mapping/uniprot-proteome_human_reviewed.fasta.veNOG.hmmer.emapper.annotations -o  eggnog_mapping/human.veNOG.mapping -l veNOG -s hmmer
